#!/usr/bin/env python3
"""Turn the cross-machine sweep into cost per proof and latency per proof.

Two numbers answer two different questions and they do not have the same winner:

  cost per proof   = $/hour * seconds per proof / 3600
                     What a saturated prover service pays. It assumes the box is busy
                     100% of the time, which is the *best* case for cloud rental and the
                     one that flatters it most. A bursty workload pays for idle too.

  latency          = seconds per proof
                     What one user waits. Buying it is a separate decision from paying
                     for it, and on this data the two winners are different machines.

Both are reported cold and warm, because they are not the same workload:

  cold  one fresh process per proof. Key parse and, on a GPU, module load and upload are
        inside the timed region. This is a CLI invocation or a lambda-style one-shot.
  warm  setup paid once, then prove in a loop. This is a resident service.

Neither is "the" number. A GPU looks good warm and bad cold, and any benchmark that
reports only one of them is choosing a conclusion rather than measuring one.

Spot is reported alongside on-demand because nobody runs a batch prover on-demand, and
the discount is not uniform: it is 60-66% on the CPU families here and 22% on the Ada
GPUs, which is large enough to reorder the ranking.
"""
import argparse, csv, json, statistics
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SWEEP = ROOT / "results" / "sweep"


def load_prices():
    od = {r["instance_type"]: float(r["usd_per_hour"])
          for r in csv.DictReader((ROOT / "aws" / "machines.csv").open())}
    spot = defaultdict(lambda: None)
    p = ROOT / "aws" / "spot-use1.csv"
    if p.exists():
        best = {}
        for r in csv.DictReader(p.open()):
            t, v = r["instance_type"], float(r["spot_usd_per_hour"])
            if t not in best or v < best[t]:
                best[t] = v
        spot.update(best)
    return od, spot


def load_sweep():
    """(machine, backend, mode, variant) -> {ms, constraints, meta}"""
    out, metas = {}, {}
    for d in sorted(SWEEP.iterdir()) if SWEEP.exists() else []:
        if not d.is_dir():
            continue
        mf = d / "meta.json"
        meta = json.loads(mf.read_text()) if mf.exists() else {"instance_type": d.name}
        metas[d.name] = meta
        for f in d.glob("*.csv"):
            if f.stem in ("meta",):
                continue
            rows = defaultdict(list)
            for r in csv.DictReader(f.open()):
                if not r.get("ms"):
                    continue
                # A rep whose proof did not verify is not a timing. Dropping it silently
                # would be the single most misleading thing this script could do, so it is
                # counted and surfaced instead.
                key = (d.name, r.get("backend") or f.stem, r["mode"], r["variant"])
                rows[key].append((float(r["ms"]), r.get("verified", "yes"), r.get("constraints")))
            for k, v in rows.items():
                good = [x[0] for x in v if x[1] in ("yes", "true", "True", "1")]
                bad = len(v) - len(good)
                if not good:
                    continue
                out[k] = dict(ms=statistics.median(good), lo=min(good), hi=max(good),
                              n=len(good), unverified=bad,
                              constraints=int(v[0][2]) if v[0][2] else -1)
    return out, metas


def per_k(usd):
    """Dollars per 1000 proofs.

    Everything here costs a fraction of a cent per proof, so a per-proof column is a row of
    leading zeros that no one can compare at a glance. Per 1000 proofs puts every machine in
    the same readable range and is the unit anyone sizing a prover fleet actually thinks in.
    """
    return f"${usd*1000:,.3f}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", default="js_16x16_d32",
                    help="headline circuit for the ranked tables")
    ap.add_argument("--out", default=str(ROOT / "results" / "COST.md"))
    args = ap.parse_args()

    od, spot = load_prices()
    data, metas = load_sweep()
    if not data:
        raise SystemExit(f"no sweep results under {SWEEP}")

    L = []
    add = L.append

    machines = sorted(metas)
    variants = sorted({k[3] for k in data}, key=lambda v: next(
        (d["constraints"] for k, d in data.items() if k[3] == v), 0))

    add("# Cost per proof, and latency per proof\n")
    add("Generated by `bench/scripts/cost.py`. Every timing below belongs to a proof that "
        "`g16 bench` verified before recording it; unverified reps are excluded and counted.\n")

    # ---- the two headline rankings ----------------------------------------------------
    v = args.variant
    for mode in ("warm", "cold"):
        rows = []
        for (m, b, md, vv), d in data.items():
            if md != mode or vv != v:
                continue
            price = od.get(m)
            meta = metas.get(m, {})
            if price is None:              # owned hardware: no rental price exists
                price = meta.get("usd_per_hour")
            if not price:
                continue
            s = d["ms"] / 1000.0
            rows.append((m, b, d["ms"], price * s / 3600,
                         (spot.get(m) or price) * s / 3600,
                         3600 / s, meta))
        if not rows:
            continue
        nc = next((d["constraints"] for k, d in data.items() if k[3] == v), -1)
        add(f"\n## {mode.capitalize()}: {v} ({nc:,} constraints)\n")
        add("**Cheapest first.** Cost assumes the box proves continuously; idle time is "
            "not modelled and would raise every row.\n")
        add("| # | machine | backend | ms/proof | $/1k proofs | $/1k spot | proofs per $ | proofs/hour |")
        add("|---|---|---|---:|---:|---:|---:|---:|")
        for i, r in enumerate(sorted(rows, key=lambda x: x[3]), 1):
            m, b, ms, c, cs, ph, meta = r
            acc = meta.get("gpu") or meta.get("cpu_model", "")[:28]
            add(f"| {i} | `{m}` <br><sub>{acc}</sub> | {b} | {ms:,.1f} | {per_k(c)} | "
                f"{per_k(cs)} | {1/c:,.0f} | {ph:,.0f} |")
        add("")
        add("**Fastest first.**\n")
        add("| # | machine | backend | ms/proof | $/1k proofs | vs fastest |")
        add("|---|---|---|---:|---:|---:|")
        fastest = min(x[2] for x in rows)
        for i, r in enumerate(sorted(rows, key=lambda x: x[2]), 1):
            m, b, ms, c, cs, ph, meta = r
            acc = meta.get("gpu") or meta.get("cpu_model", "")[:28]
            add(f"| {i} | `{m}` <br><sub>{acc}</sub> | {b} | {ms:,.1f} | {per_k(c)} | "
                f"{ms/fastest:.2f}x |")

    # ---- full grid --------------------------------------------------------------------
    add("\n## Full grid\n")
    add("Costs are dollars per 1000 proofs, at 100% utilisation.\n")
    for m in machines:
        meta = metas[m]
        price = od.get(m) or meta.get("usd_per_hour")
        backends = sorted({k[1] for k in data if k[0] == m})
        if not backends:
            continue
        gate = meta.get("tests", "?")
        add(f"\n### `{m}` — {meta.get('cpu_model','?')}"
            + (f", {meta['gpu']}" if meta.get("gpu") else "")
            + f"\n\n{meta.get('vcpu','?')} vCPU / {meta.get('cores','?')} cores, "
              f"{meta.get('mem_gib','?')} GiB, ${price}/hr on-demand"
            + (f", ${spot[m]:.4f}/hr spot" if spot.get(m) else "")
            + f". Correctness gate: **{gate}**."
            + (f" First kernel build on a fresh box: "
               f"{float(meta['first_compile_s']):.0f} s (once per machine, not per proof)."
               if meta.get("first_compile_s") else "") + "\n")
        add("| circuit | constraints | backend | mode | ms | $/1k proofs | $/1k spot |")
        add("|---|---:|---|---|---:|---:|---:|")
        for vv in variants:
            for b in backends:
                for md in ("cold", "warm"):
                    d = data.get((m, b, md, vv))
                    if not d:
                        continue
                    s = d["ms"] / 1000.0
                    c = price * s / 3600
                    cs = (spot.get(m) or price) * s / 3600
                    warn = f" ⚠{d['unverified']} unverified" if d["unverified"] else ""
                    add(f"| {vv} | {d['constraints']:,} | {b} | {md} | {d['ms']:,.1f} | "
                        f"{per_k(c)} | {per_k(cs)}{warn} |")

    Path(args.out).write_text("\n".join(L) + "\n")
    print(f"wrote {args.out}  ({len(machines)} machines, {len(data)} cells)")


if __name__ == "__main__":
    main()
