[package]
name = "snarkrs-gpu-kernels"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CUDA C kernel sources for the snarkrs CUDA backend"
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
include = ["src/**/*", "LICENSE-MIT", "LICENSE-APACHE"]
