[package]
name = "g16-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "g16"
path = "src/main.rs"

[dependencies]
g16-field.workspace = true
g16-zkey.workspace = true
g16-core.workspace = true
g16-metal = { workspace = true, optional = true }
g16-cuda  = { workspace = true, optional = true }
ark-bn254.workspace = true
ark-ff.workspace = true
ark-ec.workspace = true
ark-serialize.workspace = true
ark-std.workspace = true
clap.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
num-bigint.workspace = true
hex.workspace = true

[features]
default = ["cpu"]
cpu = []
metal = ["dep:g16-metal"]
cuda = ["dep:g16-cuda"]
